augmentation:
  train:
    ops:
      - type: RandomResizedCrop
        scale: [0.08, 1.0]
        ratio: [0.75, 1.333]
      - type: HorizontalFlip
        p: 0.5
      - type: ColorJitter
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0.1
        p: 0.8
      - type: GaussianBlur
        blur_limit: [3, 7]
        p: 0.2
      - type: CoarseDropout
        max_holes: 1
        max_height: 56
        max_width: 56
        min_holes: 1
        min_height: 28
        min_width: 28
        fill_value: 0
        p: 0.5
      - type: Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
      - type: ToTensorV2
  val:
    ops:
      - type: Resize
      - type: Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
      - type: ToTensorV2
