seed: 42
output_dir: "outputs"
exp_name: "default"

data:
  batch_size: 128
  num_workers: 8
  pin_memory: true

logger:
  type: "mlflow"
  experiment_name: "classification"
  log_model: true
  tracking_uri: sqlite:///mlflow.db
