trainer:
  max_epochs: 100
  accelerator: "gpu"
  devices: 1
  precision: "16-mixed"
  strategy: "auto"
  accumulate_grad_batches: 1
  deterministic: true
  log_every_n_steps: 100
  val_check_interval: 1.0

progress_bar:
  refresh_rate: 10

checkpoint:
  monitor: "val_loss"
  mode: "min"
  save_top_k: 1
  save_last: true
